### ISSUE TITLE
Cannot run windows executable "out of the box"

### ISSUE THREAD

**Issue by LSgeo** [TarynScharf/AnalyZr#38]
Hi Taryn,
I downloaded v0.22 (and tested v0.21 too) to check out the program. I ran the exe, and the command prompt that opened immediately closes. Investigating the error by running the exe in windows terminal shows the error message quoted below.

Additionally, I cloned the repository to run the source main.py to check it out manually, but needed to move src/main.py up a directory to get relative imports throughout the package to work properly. Maybe the structure of the imports is important for the executable, but it took a minute to figure out for running from source.

Cheers for an awesome program!

> c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:493: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "view\application_view.py", line 25, in <module>
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "model\ZirconSeparationUtils.py", line 3, in <module>
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "cv2\__init__.py", line 188, in <module>
  File "cv2\__init__.py", line 118, in bootstrap
  File "cv2\__init__.py", line 116, in load_first_config
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.
[9528] Failed to execute script main

**Comment by TarynScharf** [comment]
Hi @LSgeo,

Thanks so much for getting in touch and letting me know about the bug! Turns out something's off with the OpenCV requirement. I've updated the requirements file and released a new build that includes an additional bug fix for mask editing. The new exe works on my side, but maybe you'd like to give it a try. 

I hope you find the code useful, overall!

**Comment by LSgeo** [comment]
Perfect! It works on my end now too.
